#ifndef _GET_INT_DEFINED

double    get_int(double,double,char*,char*,char*,char*,char);
int       g30_360U_accdays(char*,char*);
int       g30_360_accdays(char*,char*);
double    get_int30_360(double,double,char*,char*,char*,char);
int       calc_days(char*,char*,int,int,char*);
double    get_rev(double,double,char*,char*,char*,int,char);
double    g30_360_rev_int(double,double,int,char*,char*,char);
double    actual_rev_int(double,double,char*,char*,char*,int);
double    get_int365(double,double,char*,char*,char*);
double    get_int360(double,double,char*,char*,char*);
#define _GET_INT_DEFINED
#endif

